
SGD regression:
	python3 simple_regression.py

regression:
	python3 regression.py

classification:
	python3 classification.py

logistic regression:
	python3 classification.py logistic

plots:
	python3 generate_plots.py