
SGDregression:
	python3 simple_regression.py

NNregression:
	python3 regression.py

NNclassification:
	python3 classification.py

logistic:
	python3 classification.py logistic

plots:
	python3 generate_plots.py